version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install boto3 opensearch-py -t .

  build:
    commands:
      - echo Packaging the Lambda function...
      - zip -r deployment.zip . 

artifacts:
  files:
    - deployment.zip
  discard-paths: yes
  base-directory: .
